# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-19 07:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('day', models.CharField(choices=[(b'monday', b'monday'), (b'tuesday', b'tuesday'), (b'wednesday', b'wednesday'), (b'thursday', b'thursday'), (b'friday', b'friday'), (b'saturday', b'saturday'), (b'sunday', b'sunday'), (b'ALL', b'ALL')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Booking')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.IntegerField()),
                ('room_type', models.CharField(choices=[(b'Single', b'Single'), (b'Double', b'Double')], max_length=50)),
                ('doubleroom_cap', models.IntegerField(default=5)),
                ('singleroom_cap', models.IntegerField(default=5)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Room'),
        ),
    ]
