# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-19 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[(b'monday', b'monday'), (b'tuesday', b'tuesday'), (b'wednesday', b'wednesday'), (b'thursday', b'thursday'), (b'friday', b'friday'), (b'saturday', b'saturday'), (b'sunday', b'sunday')], max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='booking',
            name='id',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='room',
        ),
        migrations.AddField(
            model_name='booking',
            name='doubleroomaval',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='booking',
            name='singleroomaval',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='booking',
            name='day',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.AddField(
            model_name='booking',
            name='day',
            field=models.ManyToManyField(to='api.BookingDay'),
        ),
    ]
