# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-19 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180519_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='price',
        ),
        migrations.AddField(
            model_name='price',
            name='pricedouble',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='price',
            name='pricesingle',
            field=models.IntegerField(default=0),
        ),
    ]
