# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-19 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_booking_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Booking'),
        ),
    ]
