# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-19 17:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180519_1550'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookingDay',
        ),
    ]
