# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-20 16:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20180520_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='version',
        ),
        migrations.RemoveField(
            model_name='price',
            name='version',
        ),
    ]
