# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-26 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20180520_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='pricedouble',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='price',
            name='pricesingle',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
